### PR TITLE
Change nb to enby

### PR DESCRIPTION
**Pull request by DysphoricUnicorn**
The readme lists nb as a short form for non-binary.
I've read from multiple people that it's better to say enby because NB is used by non black people of color and mixups can happen, especially when talking about marginalised communities.

I don't want to start a discussion but from what I've read it's preferred by most people.

### CODE REVIEW

**Comment by ZoeBijl** [comment]
Thank you, I think this is a good change. 

The conflict most likely comes from me updating the files you renamed. Can you please pull/rebase?

**Comment by DysphoricUnicorn** [comment]
Okay, I’ll do so as soon as I’m on my computer, which might be late since I’ve got some plans today :)

**Comment by DysphoricUnicorn** [comment]
I think the conflict should be resolved now.

**Comment by ZoeBijl** [comment]
Thank you so much for this @DysphoricUnicorn 💯 .

**Pull request merged**
